openapi: 3.0.3
info:
  description: Cars
  title: Cars Reprex
  version: "1.0.0"
paths:
  /predict_mpg:
    post:
      summary: "Predict MPG"
      responses:
        default:
          description: Default response.
      parameters: []
      requestBody:
        description: Car Attributes
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                cyl:
                  type: number
                  example: 6
                hp:
                  type: number
                  example: 150